name: Build & Attach Release Artifacts

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm i

      - name: Prune dependencies Windows
        if: runner.os == 'Windows'
        run: |
          Get-ChildItem -Path '.\node_modules' -Recurse -File -Include '*.md', '*.markdown', '*.ts', 'license', 'license*.txt', '*notice*.txt', '*.npmignore', '*.gitkeep', '*.editorconfig', '*.eslintrc', '*.jshintrc', '.travis.yml', '.zuul.yml', 'binding.gyp', '*.sln', '*.mit', '*.bsd', '*.apache2', 'funding.yml', '*.gitmodules', 'gitpod.yml', 'dependabot.yml', '*.gitignore' | Remove-Item -Force
          Get-ChildItem -Path '.\node_modules' -Directory -Recurse -Force -Filter '.github' | Remove-Item -Recurse -Force
          Get-ChildItem -Path '.\node_modules' -Directory -Recurse -Force | Sort-Object FullName -Descending | Where-Object { -not (Get-ChildItem $_.FullName -Force -ErrorAction SilentlyContinue) } | Remove-Item -Force -ErrorAction SilentlyContinue
        shell: powershell

      - name: Prune dependencies Unix
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          find "./node_modules" -type f \( \
            -iname "*.md" \
            -o -iname "*.markdown" \
            -o -iname "*.ts" \
            -o -iname "license" \
            -o -iname "license*.txt" \
            -o -iname "*notice*.txt" \
            -o -iname "*.npmignore" \
            -o -iname "*.gitkeep" \
            -o -iname "*.editorconfig" \
            -o -iname "*.eslintrc" \
            -o -iname "*.jshintrc" \
            -o -iname ".travis.yml" \
            -o -iname ".zuul.yml" \
            -o -iname "binding.gyp" \
            -o -iname "*.sln" \
            -o -iname "*.mit" \
            -o -iname "*.bsd" \
            -o -iname "*.apache2" \
            -o -iname "funding.yml" \
            -o -iname "*.gitmodules" \
            -o -iname "gitpod.yml" \
            -o -iname "dependabot.yml" \
            -o -iname "*.gitignore" \
          \) -delete
          find "./node_modules" -type d -name ".github" -prune -exec rm -rf {} +
          find "./node_modules" -type d -empty -delete
        shell: bash

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install NSIS
        if: runner.os == 'Windows'
        run: choco install nsis -y

      - name: Add NSIS to PATH
        if: runner.os == 'Windows'
        run: echo "C:\Program Files (x86)\NSIS" >> $env:GITHUB_PATH
        shell: powershell

      - name: Install Linux system deps
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            libgtk-3-dev \
            libnss3 \
            libxss1 \
            libasound2t64 \
            libatk-bridge2.0-0 \
            libdrm2 \
            libgbm1 \
            libxkbcommon0 \
            fakeroot \
            dpkg \
            rpm

      - name: Run build script Windows
        if: runner.os == 'Windows'
        run: npm run build:windows

      - name: Run build script Unix
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: npm run build:unix

      - name: Rename Windows installer with release tag
        if: runner.os == 'Windows'
        run: |
          $RELEASE_TAG = "${{ github.ref_name }}"
          $RELEASE_TAG = $RELEASE_TAG.TrimStart('v')
          Rename-Item -Path "installer/EnderLynxInstaller.exe" -NewName "EnderLynx-win32-x64-$RELEASE_TAG.exe"
        shell: powershell

      - name: Upload artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            installer/*.exe
            out/make/**/*.zip
            out/make/**/*.dmg
            out/make/**/*.deb
            out/make/**/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
